resources:
- name: repo
  type: git
  source: 
    uri: https://github.com/cdelashmutt-pivotal/cf-automateur
    branch: master

- name: version
  type: semver
  source:
    initial_version: 0.0.0
    driver: git
    uri: https://github.com/cdelashmutt-pivotal/cf-automateur
    branch: master
    file: version
    username: ((github-user))
    password: ((github-access-token))
    git_user: "Concourse CI <cdelashmutt@pivotal.io>"
    commit_message: "[skip ci] Bump version"

- name: bosh-cli
  type: github-release
  source:
    owner: cloudfoundry
    repository: bosh-cli
    access_token: ((github-access-token))

- name: om
  type: github-release
  source:
    owner: pivotal-cf
    repository: om
    access_token: ((github-access-token))

- name: credhub-cli
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: credhub-cli
    access_token: ((github-access-token))

- name: cf-automateur-docker-image
  type: docker-image
  source:
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-hub-username))/cf-automateur

jobs:
- name: publish-container
  plan:
  - get: repo
    trigger: true
  - get: bosh-cli
    trigger: true
    params:
      globs: 
      - "*linux-amd64*"
  - get: om
    trigger: true
    params:
      globs: 
      - "*linux*"
  - get: credhub-cli
    trigger: true
    params:
      globs: 
      - "*linux*"
  - get: version
    params: 
      bump: minor
  - task: make-tools-executable
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: busybox
      inputs:
      - name: bosh-cli
      - name: om
      - name: credhub-cli
      - name: repo
      outputs:
      - name: repo
      run:
        path: sh
        args: 
        - -c
        - |
          set -e
          mkdir repo/bosh-cli
          mkdir repo/om
          mkdir repo/credhub-cli
          mv bosh-cli/bosh-cli-*-linux-amd64 repo/bosh-cli/bosh
          chmod +x repo/bosh-cli/bosh
          mv om/om-linux repo/om/om
          chmod +x repo/om/om
          tar xzf credhub-cli/credhub-linux-2.4.0.tgz -C repo/credhub-cli
          chmod +x repo/credhub-cli/credhub
  - task: build-labels-file
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: busybox
      inputs:
      - name: bosh-cli
      - name: om
      - name: credhub-cli
      - name: repo
      outputs:
      - name: repo
      run:
        path: sh
        args: 
        - -c
        - |
          set -e
          echo "{ \
          \"org.opencontainers.image.created\": \"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\", \
          }" > repo/labels_file
  - put: cf-automateur-docker-image
    params:
      build: repo
      tag_as_latest: true
      tag_file: version/version
      labels_file: repo/labels_file
    get_params:
      skip_download: true
  - put: version
    params:
      file: version/version